<?php

$labels = array(
    'name' => __( 'Shortcodes',  'news-test'),
    'singular_name' => __( 'Shortcodes',   'news-test'),
    'menu_name' => __( 'Shortcodes',  'news-test'),
    'name_admin_bar' => __( 'Shortcodes',  'news-test'),
    'archives' => __( 'Shortcodes Archives',  'news-test'),
    'attributes' => __( 'Shortcodes Attributes',  'news-test'),
    'parent_item_colon' => __( 'Parent Shortcodes:',  'news-test'),
    'all_items' => __( 'All Shortcodes',  'news-test'),
    'add_new_item' => __( 'Add New Shortcode',  'news-test'),
    'add_new' => __( 'Add New',  'news-test'),
    'new_item' => __( 'New Shortcode',  'news-test'),
    'edit_item' => __( 'Edit Shortcode',  'news-test'),
    'update_item' => __( 'Update Shortcode',  'news-test'),
    'view_item' => __( 'View Shortcode',  'news-test'),
    'view_items' => __( 'View Shortcode',  'news-test'),
    'search_items' => __( 'Search Shortcode',  'news-test'),
    'not_found' => __( 'Not found',  'news-test'),
    'not_found_in_trash' => __( 'Not found in Trash',  'news-test'),
    'featured_image' => __( 'Featured Image',  'news-test'),
    'set_featured_image' => __( 'Set featured image',  'news-test'),
    'remove_featured_image' => __( 'Remove featured image',  'news-test'),
    'use_featured_image' => __( 'Use as featured image',  'news-test'),
    'insert_into_item' => __( 'Insert into Shortcode',  'news-test'),
    'uploaded_to_this_item' => __( 'Uploaded to this Shortcode',  'news-test'),
    'items_list' => __( 'Merch list',  'news-test'),
    'items_list_navigation' => __( 'Shortcode list navigation',  'news-test'),
    'filter_items_list' => __( 'Filter Shortcode list',  'news-test'),
);
$args = array(
    'label' => __( 'Shortcodes',  'news-test'),
    'description' => __( '',  'news-test'),
    'labels' => $labels,
    'menu_icon' => 'dashicons-media-code',
    'supports' => array('title', 'custom-fields'),
    'public' => true,
    'show_ui' => true,
    'show_in_menu' => true,
    'menu_position' => 5,
    'show_in_admin_bar' => true,
    'show_in_nav_menus' => true,
    'can_export' => true,
    'has_archive' => false,
    'hierarchical' => true,
    'exclude_from_search' => false,
    'show_in_rest' => true,
    'publicly_queryable' => true,
    'capability_type' => 'page',
);
register_post_type( 'custom_shortcodes', $args );
