<?php

$labels = array(
    'name' => __( 'Merch',  'news-test'),
    'singular_name' => __( 'Merch',   'news-test'),
    'menu_name' => __( 'Merch',  'news-test'),
    'name_admin_bar' => __( 'Merch',  'news-test'),
    'archives' => __( 'PortfMercholio Archives',  'news-test'),
    'attributes' => __( 'Merch Attributes',  'news-test'),
    'parent_item_colon' => __( 'Parent Merch:',  'news-test'),
    'all_items' => __( 'All Merch',  'news-test'),
    'add_new_item' => __( 'Add New Merch',  'news-test'),
    'add_new' => __( 'Add New',  'news-test'),
    'new_item' => __( 'New Merch',  'news-test'),
    'edit_item' => __( 'Edit Merch',  'news-test'),
    'update_item' => __( 'Update Merch',  'news-test'),
    'view_item' => __( 'View Merch',  'news-test'),
    'view_items' => __( 'View Merch',  'news-test'),
    'search_items' => __( 'Search Merch',  'news-test'),
    'not_found' => __( 'Not found',  'news-test'),
    'not_found_in_trash' => __( 'Not found in Trash',  'news-test'),
    'featured_image' => __( 'Featured Image',  'news-test'),
    'set_featured_image' => __( 'Set featured image',  'news-test'),
    'remove_featured_image' => __( 'Remove featured image',  'news-test'),
    'use_featured_image' => __( 'Use as featured image',  'news-test'),
    'insert_into_item' => __( 'Insert into Merch',  'news-test'),
    'uploaded_to_this_item' => __( 'Uploaded to this Merch',  'news-test'),
    'items_list' => __( 'Merch list',  'news-test'),
    'items_list_navigation' => __( 'Merch list navigation',  'news-test'),
    'filter_items_list' => __( 'Filter Merch list',  'news-test'),
);
$args = array(
    'label' => __( 'Merch',  'news-test'),
    'description' => __( '',  'news-test'),
    'labels' => $labels,
    'menu_icon' => 'dashicons-chart-bar',
    'supports' => array('title', 'thumbnail','custom-fields'),
    'public' => true,
    'show_ui' => true,
    'show_in_menu' => true,
    'menu_position' => 5,
    'show_in_admin_bar' => true,
    'show_in_nav_menus' => true,
    'can_export' => true,
    'has_archive' => false,
    'hierarchical' => true,
    'exclude_from_search' => false,
    'show_in_rest' => true,
    'publicly_queryable' => true,
    'capability_type' => 'page',
);
register_post_type( 'merch', $args );

//Category Merch
$labels = array(
    'name'              => _x( 'Category Merch', 'taxonomy general name',  'news-test'),
    'singular_name'     => _x( 'Category Merch', 'taxonomy singular name',  'news-test'),
    'search_items'      => __( 'Search Category Merch',  'news-test'),
    'all_items'         => __( 'All Category Merch',  'news-test'),
    'parent_item'       => __( 'Parent Category Merch',  'news-test'),
    'parent_item_colon' => __( 'Parent Category Merch:',  'news-test'),
    'edit_item'         => __( 'Edit Category Merch',  'news-test'),
    'update_item'       => __( 'Update Category Merch',  'news-test'),
    'add_new_item'      => __( 'Add New Category Merch',  'news-test'),
    'new_item_name'     => __( 'New Category Merch Name',  'news-test'),
    'menu_name'         => __( 'Category Merch',  'news-test'),
);
$args = array(
    'labels' => $labels,
    'description' => __( '',  'news-test'),
    'hierarchical' => true,
    'public' => true,
    'publicly_queryable' => true,
    'rewrite'          => array('slug' => 'poster'),
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_rest' => true,
    'show_tagcloud' => true,
    'query_var'    => true,
    'show_in_quick_edit' => true,
    'show_admin_column' => false,
);
register_taxonomy( 'merch_tax', array('merch', ), $args );
